const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
// const data ={
//     products: [
//         {
//           _id: '1',
//           name: 'Shipp',
//           category: 'Noise Cancellation',
//           image: '/images/d1.jpg',
//           price: 'Rs.160',
//           countInStock:10,
//           brand: ' AWL',
//           rating: 4.5,
//           numReviews: 15,
//           description:'soft and high quality',
//         },
//         {
//             _id: '2',
//             name: 'Sonix',
//             category: 'Noise Cancellation',
//             image: '/images/p1.jpg',
//             price: 'Rs.1600',
//             countInStock:0,
//             brand: 'AWL',
//             rating: 4.0,
//             numReviews: 16,
//             description:'soft and high quality',
//           },
//           {
//             _id: '3',
//             name: 'Loud',
//             category: 'Noise Cancellation',
//             image: '/images/d3.jpg',
//             price: 'Rs.1200',
//             brand: 'Bass',
//             rating: 4.5,
//             countInStock:10,
//             numReviews: 10,
//             description:'soft and high quality',
//           },
//           {
//             _id: '4',
//             name: 'Rooster',
//             category: 'Wireless',
//             image: '/images/p1.jpg',
//             price: 'Rs.1260',
//             countInStock:10,
//             brand: 'Bass',
//             rating: 3.0,
//             numReviews: 13,
//             description:'soft and high quality',
//           },
//           {
//             _id: '5',
//             name: 'Willow',
//             category: 'Wireless',
//             image: '/images/p2.jpg',
//             price: 'Rs.3600',
//             brand: ' AWL',
//             countInStock:15,
//             rating: 4.5,
//             numReviews: 14,
//             description:'soft and high quality',
//           },
//           {
//             _id: '6',
//             name: 'Tuneit',
//             category: 'Wireless',
//             image: '/images/p3.jpg',
//             price: 'Rs.1160',
//             brand: 'AWL',
//             countInStock:0,
//             rating: 4.0,
//             numReviews: 17,
//             description:'soft and high quality',
//           },

//     ],
// };
// export default data;